server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/cookup?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.lzkydh.model



